#!/bin/bash

TheSkyX_Install=~/Library/Application\ Support/Software\ Bisque/TheSkyX\ Professional\ Edition/TheSkyXInstallPath.txt
echo "TheSkyX_Install = $TheSkyX_Install"

if [ ! -f "$TheSkyX_Install" ]; then
    echo TheSkyXInstallPath.txt not found
    exit 1
fi


TheSkyX_Path=$(<"$TheSkyX_Install")
echo "Installing to $TheSkyX_Path"

if [ ! -d "$TheSkyX_Path" ]; then
    echo TheSkyX Install dir not exist
    exit 1
fi

cp "/tmp/maxdomeII_X2/domelist MaxDomeII.txt" "$TheSkyX_Path/Resources/Common/Miscellaneous Files/"
cp "/tmp/maxdomeII_X2/maxdomeII.ui" "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/"
cp "/tmp/maxdomeII_X2/maxdomeII.png" "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/"
cp "/tmp/maxdomeII_X2/libmaxdomeII.dylib" "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/"

app_owner=`/usr/bin/stat -n -f "%u" "$TheSkyX_Path" | xargs id -n -u`
if [ ! -z "$app_owner" ]; then
	chown $app_owner "$TheSkyX_Path/Resources/Common/Miscellaneous Files/domelist MaxDomeII.txt"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/maxdomeII.ui"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/maxdomeII.png"
	chown $app_owner "$TheSkyX_Path/Resources/Common/PlugIns/DomePlugIns/libmaxdomeII.dylib"
fi

rm -rf /tmp/maxdomeII_X2

